version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  # Only do security updates. Ignore everything.
  open-pull-requests-limit: 0
  ignore:
  - dependency-name: '*'
