name: Karma tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - run: npm test
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"